[package]
name = "folktunefinder-abc"
version = "0.1.0"
authors = ["Joe Wass <joe@afandian.com>"]


[[bin]]
name = "abctool"
doc = false
path = "src/main.rs"

[dependencies]
glob = "0.2.11"
time = "0.1"
regex = "0.2"
tiny_http = "0.5"
